services:
  db:
    image: pgvector/pgvector:pg16
    restart: always
    environment:
      - POSTGRES_DB=ibot
      - POSTGRES_USER=ibot
      - POSTGRES_PASSWORD=ibot
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
